apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
data:
  PORT: "5002"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "app-reservas"
  DB_DIALECT: "postgres"
  USER_SERVICE_URL: "http://user-service:5001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5002"
apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
data:
  NODE_ENV: production
